language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

before_install:
  - pip install Cython

install: python setup.py bootstrap install

before_script: pip install nose

script:
  - python runtests.py -v
  - nosetests -v

